spring:
  application:
    name: SMSinmungo
  redis:
    host: localhost
    port: 6380

  datasource:
    url: jdbc:mariadb://localhost:3306/upcraft
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: eksldpf13

server:
  port: 8443
  ssl:
    enabled: true
    key-store: "C:/SMSinmungo/keystore.p12"
    key-store-password: "keystore"
    key-store-type: PKCS12
    key-alias: "tomcat"
    protocol: TLS
    enabled-protocols: TLSv1.2

jwt:
  issuer: am030818@naver.com
  secret-key: springboot-project-board-springboot-project-board-springboot-project-board
  access-expiration: 3600
  refresh-expiration: 86400