spring:
  application:
    name: SMSinmungo
  redis:
    host: localhost
    port: 6380
  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdb`alroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"
    #issuer: am030818@naver.com
    #secret-key: springboot-project-board-springboot-project-board-springboot-project-board
    #access-expiration: 3600
    #refresh-expiration: 86400
  mail:
    host: smtp.gmail.com  # Gmail의 SMTP 서버 호스트
    port: 587 # Gmail SMTP 서버는 587번 포트를 사용
    username: tommys915@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 인증 필요한 경우 true로 지정 Gmail은 요구함
          starttls:
            enable: true # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connection-timeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          write timeout: 5000 # 클라이언트가 작업을 완료하는데 대기해야 하는 시간
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분 이메일 인증 코드의 만료 시간(Millisecond)

profiles:
    active: local

server:
  port: 8080
  address: 0.0.0.0

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html




jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

