spring:
  application:
    name: SMSinmungo
  redis:
    host: localhost
    port: 6380
  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:

server:
  port: 8080
  address: 0.0.0.0

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  issuer: am030818@naver.com
  secret-key: springboot-project-board-springboot-project-board-springboot-project-board
  access-expiration: 3600
  refresh-expiration: 86400