spring:
  application:
    name: SMSinmungo
  redis:
    host: localhost
    port: 6380
  datasource:
    url: jdbc:mariadb://localhost:3306/upcraft
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: { password }

server:
  port: 8080

jwt:
  issuer: am030818@naver.com
  secret-key: springboot-project-board-springboot-project-board-springboot-project-board
  access-expiration: 3600
  refresh-expiration: 86400