apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsinmungo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smsinmungo
  template:
    metadata:
      labels:
        app: smsinmungo
    spec:
      containers:
        - name: smsinmungo-container
          image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/docker/smsinmungo:latest
          ports:
            - containerPort: 8080
