name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image to Google Container Registry
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT }}/SMSinmungo
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to GKE
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
          kubectl set image deployment/your-deployment-name your-container=$IMAGE_NAME:latest
